### ISSUE TITLE
uu is not useless anymore

### ISSUE THREAD

**Issue by Sofronio** [cnbeining/BiliLeupload#1]
最近A站投稿获得的VU直接投B站发现不能过审核，说是不能播放
后来发现直接访问诸如http://yuntv.letv.com/bcloud.swf?uu=iamuseless&vu=cd09b2f515的链接，UU必须和VU保持对应，否则letv已经不给解析了。

所以现在只用VU投稿B站已经不行了，B站没有填写UU的地方。必须两家分别上传。

**Comment by cnbeining** [comment]
Known issue.

AC的部分请看 https://github.com/cnbeining/acupload 。

懒癌，没改文档。。。。下个版本会修。

话说我很喜欢您在AC的Topgear系列~里面的特效真是太漂亮了。 
我的邮箱是cnbeining[at]gmail.com  加个好友吧~之前想私信戳，没敢。。。。
我用的账号是@ACICFG  ....

**Comment by cnbeining** [comment]
Fixed.
